// <auto-generated />
using System;
using BotAgendamentoAI.Telegram.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotAgendamentoAI.Telegram.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Role");

                    b.HasIndex("TenantId", "TelegramUserId")
                        .IsUnique();

                    b.ToTable("tg_Users", (string)null);
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressText")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FinalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PreferenceCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProviderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientUserId", "CreatedAt");

                    b.HasIndex("ProviderUserId", "Status", "UpdatedAt");

                    b.HasIndex("TenantId", "Status", "CreatedAt");

                    b.ToTable("tg_Jobs", (string)null);
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.JobPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramFileId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "CreatedAt");

                    b.ToTable("tg_JobPhotos", (string)null);
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.MessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RelatedJobId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelatedJobId", "CreatedAt");

                    b.HasIndex("TenantId", "TelegramUserId", "CreatedAt");

                    b.ToTable("tg_MessagesLog", (string)null);
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.ProviderPortfolioPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileIdOrUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProviderProfileUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProviderUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderProfileUserId");

                    b.HasIndex("ProviderUserId", "CreatedAt");

                    b.ToTable("tg_ProviderPortfolioPhotos", (string)null);
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.ProviderProfile", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<double?>("BaseLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("BaseLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadiusKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("tg_ProvidersProfile", (string)null);
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.Rating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProviderUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("ProviderUserId", "CreatedAt");

                    b.ToTable("tg_Ratings", (string)null);
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.ServiceCategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("tg_service_categories", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.SharedSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("setting_value");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("SettingKey");

                    b.ToTable("tg_shared_settings", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.TelegramTenantConfig", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<string>("BotId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bot_id");

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bot_token");

                    b.Property<string>("BotUsername")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bot_username");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<long>("LastUpdateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_update_id");

                    b.Property<int>("PollingTimeoutSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("polling_timeout_seconds");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("TenantId");

                    b.ToTable("tg_tenant_telegram_config", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.TenantBotConfig", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<string>("MenuJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("menu_json");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("messages_json");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("TenantId");

                    b.ToTable("tg_tenant_bot_config", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.UserSession", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActiveJobId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChatJobId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ChatPeerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChatActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("ActiveJobId");

                    b.ToTable("tg_UserSessions", (string)null);
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.Job", b =>
                {
                    b.HasOne("BotAgendamentoAI.Telegram.Domain.Entities.AppUser", "ClientUser")
                        .WithMany("ClientJobs")
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BotAgendamentoAI.Telegram.Domain.Entities.AppUser", "ProviderUser")
                        .WithMany("ProviderJobs")
                        .HasForeignKey("ProviderUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientUser");

                    b.Navigation("ProviderUser");
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.JobPhoto", b =>
                {
                    b.HasOne("BotAgendamentoAI.Telegram.Domain.Entities.Job", "Job")
                        .WithMany("Photos")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.ProviderPortfolioPhoto", b =>
                {
                    b.HasOne("BotAgendamentoAI.Telegram.Domain.Entities.ProviderProfile", null)
                        .WithMany("PortfolioPhotos")
                        .HasForeignKey("ProviderProfileUserId");

                    b.HasOne("BotAgendamentoAI.Telegram.Domain.Entities.AppUser", "ProviderUser")
                        .WithMany()
                        .HasForeignKey("ProviderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderUser");
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.ProviderProfile", b =>
                {
                    b.HasOne("BotAgendamentoAI.Telegram.Domain.Entities.AppUser", "User")
                        .WithOne("ProviderProfile")
                        .HasForeignKey("BotAgendamentoAI.Telegram.Domain.Entities.ProviderProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.Rating", b =>
                {
                    b.HasOne("BotAgendamentoAI.Telegram.Domain.Entities.Job", "Job")
                        .WithMany("Ratings")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("BotAgendamentoAI.Telegram.Domain.Entities.AppUser", "User")
                        .WithOne("Session")
                        .HasForeignKey("BotAgendamentoAI.Telegram.Domain.Entities.UserSession", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("ClientJobs");

                    b.Navigation("ProviderJobs");

                    b.Navigation("ProviderProfile");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.Job", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("BotAgendamentoAI.Telegram.Domain.Entities.ProviderProfile", b =>
                {
                    b.Navigation("PortfolioPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}

